modLoader="javafml"
loaderVersion="[${loader_version},)"
issueTrackerURL="https://github.com/Yunus1903/ChatEmbeds/issues"

[[mods]]
    modId="chatembeds"
    version="${version}"
    displayName="Chat Embeds"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/chat-embeds"
    logoFile="chatembeds.png"

    authors="Yunus1903"
    credits=""
    description="Embedded images and more in chat!"

[[dependencies.chatembeds]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"
[[dependencies.chatembeds]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
